create table if not exists roles
(
    id   bigint generated by default as identity,
    name varchar(255) not null,
    constraint roles_id_PK primary key (id),
    constraint roles_name_AK unique (name)
);
create table if not exists states
(
    id   bigint generated by default as identity,
    name varchar(255) not null,
    constraint states_id_PK primary key (id),
    constraint states_id_UQ unique (name)
);
create table if not exists users
(
    id         bigint generated by default as identity,
    email      varchar(255) not null,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    password   varchar(255) not null,
    role_id    bigint,
    constraint users_id_PK primary key (id),
    constraint users_role_id_FK foreign key (role_id) references roles,
    constraint users_email_AK unique (email)
);
create table if not exists todos
(
    id          bigint generated by default as identity,
    created_at  timestamp    not null,
    title       varchar(255) not null,
    description varchar(255),
    owner_id    bigint,
    constraint todos_id_PK primary key (id),
    constraint todos_user_id_FK foreign key (owner_id) references users,
    constraint todos_title_AK unique (title)
);
create table if not exists tasks
(
    id          bigint generated by default as identity,
    name        varchar(255) not null,
    description varchar(255),
    priority    varchar(255),
    state_id    bigint,
    todo_id     bigint,
    constraint tasks_id_PK primary key (id),
    constraint tasks_todos_id_FK foreign key (todo_id) references todos,
    constraint tasks_states_id_FK foreign key (state_id) references states
);
create table if not exists todos_collaborators
(
    todo_id         bigint not null,
    collaborator_id bigint not null,
    constraint todos_collaborators_PK primary key (todo_id, collaborator_id),
    constraint todos_collaborators_todo_id_FK foreign key (todo_id) references todos,
    constraint todos_collaborators_collaborator_id_FK foreign key (collaborator_id) references users
);
